version: '3.8'

services:
  load_balancer:
    build:
      context: .
      dockerfile: ./load_balancer/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_ENV=development

 