version: '3.8'

services:
  server1:
    build:
      context: ./my_webserver2
    ports:
      - "5001:5000"
    environment:
      - SERVER_ID=1

  server2:
    build:
      context: ./my_webserver2
    ports:
      - "5002:5000"
    environment:
      - SERVER_ID=2

  server3:
    build:
      context: ./my_webserver2
    ports:
      - "5003:5000"
    environment:
      - SERVER_ID=3
